######## network-policies.yaml 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: votes-ui-netpol
spec:
  podSelector:
    matchLabels:
      app: votes-ui
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Permite tráfico desde ingress
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  # Permite tráfico interno del namespace
  - from:
    - podSelector: {}
  egress:
  # Permite comunicación con votes-api
  - to:
    - podSelector:
        matchLabels:
          app: votes-api
  # DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: votes-api-netpol
spec:
  podSelector:
    matchLabels:
      app: votes-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: votes-ui
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to: []
    ports:
    - protocol: UDP
      port: 53

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-netpol
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: votes-api
    ports:
    - protocol: TCP
      port: 5432
  egress:
  - to: []
    ports:
    - protocol: UDP
      port: 53
