######## templates/secrets.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: "postgres"
  password: {{ .Values.postgresql.auth.password | quote }}
  database: {{ .Values.postgresql.auth.database | quote }}
  host: "postgres-service"
